name: DrkEngine CI
on:
  push:
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  Linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run:  scripts/build.sh --debug --tests --console_chess

      - name: Run Tests
        run:  scripts/run.sh --debug --tests
