# name: Unit Tests
# on: [push]
# 
# env:
#   BUILD_TYPE: Debug
# 
# jobs:
#   Linux Test:
#     runs-on: ubuntu-latest
#     steps:
#         - uses: actions/checkout@v2
#           shell: bash
# 
#         - name: Build Test
#           run: scripts/buildtest.sh
# 
#         - name: Run Test
#           run: scripts/runtest.sh
# 
#   Windows Test:
#     runs-on: windows-latest
#     steps:
#         - uses: actions/checkout@v2
#           shell: pswh
# 
#         - name: Build Test
#           run: scripts/buildtest.bat
# 
#         - name: Run Test
#           run: scripts/runtest.bat
