name: Unit Tests
on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  Linux-Build:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash

    steps:
        - uses: actions/checkout@v2

        - name: Build Tests
          run: scripts/buildtests.sh

        - name: Run Tests
          run: scripts/runtests.sh

#   Windows-Build:
#     runs-on: windows-latest
#     defaults:
#       run:
#         shell: cmd
# 
#     steps:
#         - uses: actions/checkout@v2
# 
#         - name: Build Tests
#           run: scripts/buildtests.bat
# 
#         - name: Run Tests
#           run: scripts/runtests.bat
